### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by miromichalicka** [priznanie-digital/priznanie-digital#366]
- Predmet emailu a nadpis v nom obsahuju 2019.
- Email prisiel do spamu (gmail)

**Comment by jsuchal** [comment]
@miromichalicka ahoj, ten rok bol fixnuty, so spamom je to tazsie, vies poslat original raw message z gmailu nech vidime na com to pada?

**Comment by miromichalicka** [comment]
poslane emailom

**Comment by jsuchal** [comment]
Diky, s tymto velmi neviem co. Hlavicky su dobre, pouzivame sendinblue/aws, ktori sice sem tam skocia na spam list ale maju dobru deliverability.

**Comment by jsuchal** [comment]
Zatvorim toto, vyriesime to nejakou hlaskou, ze si maju ludia overit, ze to maju na emaili.
